// <auto-generated />
using System;
using DotLanches.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotLanches.Infra.Migrations
{
    [DbContext(typeof(DotLanchesDbContext))]
    [Migration("20240521013020_AddPedidoAndCombo")]
    partial class AddPedidoAndCombo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotLanches.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcompanhamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("AcompanhamentoName")
                        .HasColumnType("text");

                    b.Property<int?>("BebidaId")
                        .HasColumnType("integer");

                    b.Property<string>("BebidaName")
                        .HasColumnType("text");

                    b.Property<int?>("LancheId")
                        .HasColumnType("integer");

                    b.Property<string>("LancheName")
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("SobremesaId")
                        .HasColumnType("integer");

                    b.Property<string>("SobremesaName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhamentoId");

                    b.HasIndex("BebidaId");

                    b.HasIndex("LancheId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("SobremesaId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteCPF")
                        .HasColumnType("text")
                        .HasColumnName("ClienteCPF");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCPF");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Combo", b =>
                {
                    b.HasOne("DotLanches.Domain.Entities.Produto", "Acompanhamento")
                        .WithMany()
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DotLanches.Domain.Entities.Produto", "Bebida")
                        .WithMany()
                        .HasForeignKey("BebidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DotLanches.Domain.Entities.Produto", "Lanche")
                        .WithMany()
                        .HasForeignKey("LancheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DotLanches.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Combos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotLanches.Domain.Entities.Produto", "Sobremesa")
                        .WithMany()
                        .HasForeignKey("SobremesaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acompanhamento");

                    b.Navigation("Bebida");

                    b.Navigation("Lanche");

                    b.Navigation("Pedido");

                    b.Navigation("Sobremesa");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("DotLanches.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteCPF")
                        .HasPrincipalKey("Cpf");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Produto", b =>
                {
                    b.HasOne("DotLanches.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DotLanches.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Combos");
                });
#pragma warning restore 612, 618
        }
    }
}
