apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotlanche-persistent-volume-claim
  labels: 
    app: dotlanche-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage